In [53]:
import numpy as np
import pandas as pd
import math

In [3]:
nzp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
nks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

np.cov(nzp,nks)

In [ ]:
#1.Найдите ковариацию этих двух величин с помощью элементарных действий,
#  а затем с помощью функции cov из numpy Полученные значения должны быть равны. 
#  Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, 
#  а затем с использованием функций из библиотек numpy и pandas.

In [41]:
stdNzp = np.std(nzp,ddof=1)
print(stdNzp)

62.31318747531162


In [42]:
stdNks = np.std(nks,ddof=1)
print(stdNks)

183.99544076477068


In [46]:
#cov_xy = M(xy)-M(x)*M(Y)
covNzpNks = np.mean(nzp*nks)-np.mean(nzp)*np.mean(nks)
print(covNzpNks)

9157.839999999997


In [47]:
npcov0 = np.cov(nzp,nks,ddof=0)
print(npcov0)

[[ 3494.64  9157.84]
 [ 9157.84 30468.89]]


In [43]:
npcov = np.cov(nzp,nks,ddof=1)
print(npcov)

[[ 3882.93333333 10175.37777778]
 [10175.37777778 33854.32222222]]


In [44]:
# koef Pirson rxy = cov_xy/(sigmaX*sigmaY)
rPirs = npcov /(stdNzp*stdNks)
print(rPirs)


[[0.33866702 0.88749009]
 [0.88749009 2.95275283]]


In [45]:
np.corrcoef(nzp,nks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [51]:
#2.Измерены значения IQ выборки студентов,
#  обучающихся в местных технических вузах:
#    131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
#    Известно, что в генеральной совокупности IQ распределен нормально.
#    Найдите доверительный интервал для математического ожидания с надежностью 0.95.

npa = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

print(f"mean {npa.mean()}")
print(f"sdt {np.std(npa, ddof=1)}")
maxval = npa.mean()+2.262*np.std(npa, ddof=1)/10
minval = npa.mean()-2.262*np.std(npa, ddof=1)/10
print(f"интервал {minval} - {maxval}")

# Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности,
#  равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. 
# Найдите доверительный интервал для математического ожидания с надежностью 0.95
.

mean 118.1
sdt 10.54566788359614
интервал 115.71456992473054 - 120.48543007526945


In [56]:
# формула X+-Za/2*Sigma/sqrt(n)

dmin=174.2-1.96*5/math.sqrt(27)
dmax=174.2+1.96*5/math.sqrt(27)
print(f"интервал {dmin} - {dmax}")

интервал 172.31398912064722 - 176.08601087935276
